### PR TITLE
export flag to ensure go mod installs deps

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
```

**Comment by arapov** [comment]
The intention is good, though the implementation I don't like. We must not enforce developer's  environment for regular builds. This will be unfriendly.

This deserves a better build documentation and special build target in Makefile, so that a non-developer can actually get the binary.

**Comment by arapov** [comment]
@alexander-demichev, let's discuss this tomorrow so that you can do the necessary changes to this pull request.

**Comment by jmontleon** [comment]
@jwmatthews thank you clarifying.  It looks like all that's really needed is for GO111MODULE=on to be set for the build. `go mod vendor` is unnecessary.

**Pull request merged**
