### PR TITLE
[WIP] Create Image CR for registry configuration

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by alexander-demichev** [comment]
Overall looks looks good, are you planning to add tests later? Could you also update example config?

**Comment by jmontleon** [comment]
Added WIP tag. Still working on it.

**Comment by gildub** [comment]
@jmontleon, 

+1 for encapsulating with the registries.

Meanwhile I wonder why changing the decode core and using toml. 
The closest we stay from OCP3 libraries the better (unless there is a good reason to). We're already  mapping OCP3 and ideally @arapov  and I were thinking do the same with OCP structure and tap into their libraries.

**Comment by gildub** [comment]
I sugest separating the registries code from the decode part in 2 different PRs.

**Comment by gildub** [comment]
Sorry I posted and removed 2 comments that are not relevant.
This LGTM
+1 for tests

**Comment by jmontleon** [comment]
Closing. This is included in #128.

**Pull request closed without merging**
