### PR TITLE
Fix lint errors

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
@eriknelson are you ok with the function renames? Lint was complaining that Transform.TransformRunner was a stutter and suggested changing it to Transform.Runner, etc.

**Comment by eriknelson** [comment]
@jmontleon I was often guilty of lint problems for this very reason with the broker. It still feels unnatural to me but I understand and agree with the reasoning.

**Comment by jmontleon** [comment]
Think it should be fixed now.

**Comment by eriknelson** [comment]
Fixed for me.

**Pull request merged**
